ALTER TYPE "ContactCustomFieldType" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "ContactCustomFieldType" ADD VALUE IF NOT EXISTS 'CURRENCY';
ALTER TYPE "ContactCustomFieldType" ADD VALUE IF NOT EXISTS 'DATE';
